---
# @see https://aws.amazon.com/jp/premiumsupport/knowledge-center/ec2-enable-epel/
- name: calculate epel yum repository to install
  set_fact:
    epel_yum_repository: "{{ 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm' if ansible_distribution == 'Amazon' and ansible_service_mgr == 'sysvinit' else 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm' if ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' else 'epel-release' }}"

- name: install epel yum repository to install ius repository
  yum:
    name: "{{ epel_yum_repository }}"

- name: calculate rhel version to install ius repository
  set_fact:
    rhel_version: "{{ '7' if ansible_distribution == 'Amazon' and ansible_service_mgr == 'sysvinit' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' else '6' }}"

- name: install ius repository
  yum:
    name: https://rhel{{ rhel_version }}.iuscommunity.org/ius-release.rpm

- name: install apache
  yum:
    name:
      - httpd24u
      - httpd24u-tools

- name: set running user and group
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - regexp: ^User\s.*$
      replace: User {{ apache_2_4_running_user }}
    - regexp: ^Group\s.*$
      replace: Group {{ apache_2_4_running_user }}

- name: add deploy user into apache group
  user:
    groups: '{{ apache_2_4_running_user }}'
    name: '{{ roles_common_deploy_user }}'

- name: set umask to add writable permission for apache group users
  lineinfile:
    path: /etc/sysconfig/httpd
    line: umask 002

- name: enable service on boot (excluding case when docker container)
  service:
    name: httpd
    enabled: "{{ 'no' if 'container' in group_names else 'yes' }}"
  when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: set logrotate as daily
  blockinfile:
    path: /etc/logrotate.d/httpd
    insertafter: ^\s*endscript$
    block: |
      daily
